# Generated by Django 3.1.4 on 2021-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_auto_20210308_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
