# Generated by Django 3.1.4 on 2021-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0003_customuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
