# Generated by Django 3.1.1 on 2021-03-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_auto_20210308_1742'),
        ('rent_app', '0004_auto_20210308_1813'),
    ]

    operations = [
    ]
