# Generated by Django 3.1.4 on 2021-03-09 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_merge_20210309_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phoneno',
            field=models.CharField(blank=True, default=1111111111, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
