# Generated by Django 3.1.4 on 2021-03-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0006_auto_20210309_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('rent', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('image', models.ImageField(upload_to='house_images/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=20)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'house_id')},
            },
        ),
    ]
