# Generated by Django 3.1.4 on 2021-03-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0007_auto_20210309_1436'),
        ('rent_app', '0006_auto_20210309_1409'),
    ]

    operations = [
    ]
