# Generated by Django 3.1.4 on 2021-03-26 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0009_auto_20210323_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rented_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='house',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
